npm install @types/node@latest
npm install @types/react@latest
npm install @types/react-dom@latest
npm install @types/react-transition-group@latest
npm install core-js@latest
npm install express@latest
npm install fbjs@latest
npm install multiparty@latest
npm install mysql@latest
npm install node@latest
npm install path@latest
npm install react@latest
npm install react-children@latest
npm install react-dom@latest
npm install react-dom-server@latest
npm install react-transition-group@latest
npm install react-universal@latest
npm install react-universal-component@latest
npm install request@latest
npm install ts-loader@latest
npm install typescript@latest
npm install util@latest
npm install webpack@latest
npm install webpack-cli@latest
