start transaction;

insert into lookups values 
	(null, 236, 2, "AL", "Alabama", "State", true, now(), now()),
	(null, 236, 2, "AK", "Alaska", "State", true, now(), now()),
	(null, 236, 2, "AZ", "Arizona", "State", true, now(), now()),
	(null, 236, 2, "AR", "Arkansas", "State", true, now(), now()),
	(null, 236, 2, "CA", "California", "State", true, now(), now()),
	(null, 236, 2, "CZ", "Canal Zone", "Zone", true, now(), now()),
	(null, 236, 2, "CO", "Colorado", "State", true, now(), now()),
	(null, 236, 2, "CT", "Connecticut", "State", true, now(), now()),
	(null, 236, 2, "DE", "Delaware", "State", true, now(), now()),
	(null, 236, 2, "DC", "District of Columbia", "District", true, now(), now()),
	(null, 236, 2, "FL", "Florida", "State", true, now(), now()),
	(null, 236, 2, "GA", "Georgia", "State", true, now(), now()),
	(null, 236, 2, "HI", "Hawaii", "State", true, now(), now()),
	(null, 236, 2, "ID", "Idaho", "State", true, now(), now()),
	(null, 236, 2, "IL", "Illinois", "State", true, now(), now()),
	(null, 236, 2, "IN", "Indiana", "State", true, now(), now()),
	(null, 236, 2, "IA", "Iowa", "State", true, now(), now()),
	(null, 236, 2, "KS", "Kansas", "State", true, now(), now()),
	(null, 236, 2, "KY", "Kentucky", "State", true, now(), now()),
	(null, 236, 2, "LA", "Louisiana", "State", true, now(), now()),
	(null, 236, 2, "ME", "Maine", "State", true, now(), now()),
	(null, 236, 2, "MD", "Maryland", "State", true, now(), now()),
	(null, 236, 2, "MA", "Massachusetts", "State", true, now(), now()),
	(null, 236, 2, "MI", "Michigan", "State", true, now(), now()),
	(null, 236, 2, "MN", "Minnesota", "State", true, now(), now()),
	(null, 236, 2, "MS", "Mississippi", "State", true, now(), now()),
	(null, 236, 2, "MO", "Missouri", "State", true, now(), now()),
	(null, 236, 2, "MT", "Montana", "State", true, now(), now()),
	(null, 236, 2, "NE", "Nebraska", "State", true, now(), now()),
	(null, 236, 2, "NV", "Nevada", "State", true, now(), now()),
	(null, 236, 2, "NH", "New Hampshire", "State", true, now(), now()),
	(null, 236, 2, "NJ", "New Jersey", "State", true, now(), now()),
	(null, 236, 2, "NM", "New Mexico", "State", true, now(), now()),
	(null, 236, 2, "NY", "New York", "State", true, now(), now()),
	(null, 236, 2, "NC", "North Carolina", "State", true, now(), now()),
	(null, 236, 2, "ND", "North Dakota", "State", true, now(), now()),
	(null, 236, 2, "OH", "Ohio", "State", true, now(), now()),
	(null, 236, 2, "OK", "Oklahoma", "State", true, now(), now()),
	(null, 236, 2, "OR", "Oregon", "State", true, now(), now()),
	(null, 236, 2, "PA", "Pennsylvania", "State", true, now(), now()),
	(null, 236, 2, "RI", "Rhode Island", "State", true, now(), now()),
	(null, 236, 2, "SC", "South Carolina", "State", true, now(), now()),
	(null, 236, 2, "SD", "South Dakota", "State", true, now(), now()),
	(null, 236, 2, "TN", "Tennessee", "State", true, now(), now()),
	(null, 236, 2, "TX", "Texas", "State", true, now(), now()),
	(null, 236, 2, "UT", "Utah", "State", true, now(), now()),
	(null, 236, 2, "VT", "Vermont", "State", true, now(), now()),
	(null, 236, 2, "VA", "Virginia", "State", true, now(), now()),
	(null, 236, 2, "WA", "Washington", "State", true, now(), now()),
	(null, 236, 2, "WV", "West Virginia", "State", true, now(), now()),
	(null, 236, 2, "WI", "Wisconsin", "State", true, now(), now()),
	(null, 236, 2, "WY", "Wyoming", "State", true, now(), now());

commit;

select * from lookups where reference_id = 236;