start transaction;

insert into lookups values
	(null, null, 1, "Afghanistan", null),
	(null, null, 1, "Albania", "Republic of Albania"),
	(null, null, 1, "Algeria", "People's Democratic Republic of Algeria"),
	(null, null, 1, "Andorra", "Principality of Andorra"),
	(null, null, 1, "Angola", "Republic of Angola"),
	(null, null, 1, "Antigua and Barbuda", null),
	(null, null, 1, "Argentina", "Argentine Republic"),
	(null, null, 1, "Armenia", "Republic of Armenia"),
	(null, null, 1, "Artsakh", null),
	(null, null, 1, "Australia", "Commonwealth of Australia"),
	(null, null, 1, "Austria", "Republic of Austria"),
	(null, null, 1, "Azerbaijan", "Republic of Azerbaijan"),
	(null, null, 1, "Bahamas, The", "Commonwealth of The Bahamas"),
	(null, null, 1, "Bahrain", "Kingdom of Bahrain"),
	(null, null, 1, "Bangladesh", "People's Republic of Bangladesh"),
	(null, null, 1, "Barbados", null),
	(null, null, 1, "Belarus", "Republic of Belarus"),
	(null, null, 1, "Belgium", "Kingdom of Belgium"),
	(null, null, 1, "Belize", null),
	(null, null, 1, "Benin", "Republic of Benin"),
	(null, null, 1, "Bhutan", "Kingdom of Bhutan"),
	(null, null, 1, "Bolivia", "Plurinational State of Bolivia"),
	(null, null, 1, "Bosnia and Herzegovina", null),
	(null, null, 1, "Botswana", "Republic of Botswana"),
	(null, null, 1, "Brazil", "Federative Republic of Brazil"),
	(null, null, 1, "Brunei", "Nation of Brunei, the Abode of Peace"),
	(null, null, 1, "Bulgaria", "Republic of Bulgaria"),
	(null, null, 1, "Burkina Faso", null),
	(null, null, 1, "Burundi", "Republic of Burundi"),
	(null, null, 1, "Cambodia", "Kingdom of Cambodia"),
	(null, null, 1, "Cameroon", "Republic of Cameroon"),
	(null, null, 1, "Canada", null),
	(null, null, 1, "Cape Verde", "Republic of Cabo Verde"),
	(null, null, 1, "Central African Republic", null),
	(null, null, 1, "Chad", "Republic of Chad"),
	(null, null, 1, "Chile", "Republic of Chile"),
	(null, null, 1, "China", "People's Republic of China"),
	(null, null, 1, "Colombia", "Republic of Colombia"),
	(null, null, 1, "Comoros", "Union of the Comoros"),
	(null, null, 1, "Congo", "Democratic Republic of the Congo"),
	(null, null, 1, "Cook Islands", null),
	(null, null, 1, "Costa Rica", "Republic of Costa Rica"),
	(null, null, 1, "Croatia", "Republic of Croatia"),
	(null, null, 1, "Cuba", "Republic of Cuba"),
	(null, null, 1, "Cyprus", "Republic of Cyprus"),
	(null, null, 1, "Czech Republic", null),
	(null, null, 1, "Denmark Denmark", "Kingdom of Denmark"),
	(null, null, 1, "Djibouti", "Republic of Djibouti"),
	(null, null, 1, "Dominica", "Commonwealth of Dominica"),
	(null, null, 1, "Dominican Republic", null),
	(null, null, 1, "Donetsk People's Republic", null),
	(null, null, 1, "East Timor", "Democratic Republic of Timor-Leste"),
	(null, null, 1, "Ecuador", "Republic of Ecuador"),
	(null, null, 1, "Egypt", "Arab Republic of Egypt"),
	(null, null, 1, "El Salvador", "Republic of El Salvador"),
	(null, null, 1, "Equatorial Guinea", "Republic of Equatorial Guinea"),
	(null, null, 1, "Eritrea", "State of Eritrea"),
	(null, null, 1, "Estonia", "Republic of Estonia"),
	(null, null, 1, "Eswatini", "Kingdom of Eswatini"),
	(null, null, 1, "Ethiopia", "Federal Democratic Republic of Ethiopia"),
	(null, null, 1, "Fiji", "Republic of Fiji"),
	(null, null, 1, "Finland", "Republic of Finland"),
	(null, null, 1, "France", "French Republic"),
	(null, null, 1, "Gabon", "Gabonese Republic"),
	(null, null, 1, "Gambia, The", "Republic of The Gambia"),
	(null, null, 1, "Georgia", null),
	(null, null, 1, "Germany", "Federal Republic of Germany"),
	(null, null, 1, "Ghana", "Republic of Ghana"),
	(null, null, 1, "Greece", "Hellenic Republic"),
	(null, null, 1, "Grenada", null),
	(null, null, 1, "Guatemala", "Republic of Guatemala"),
	(null, null, 1, "Guinea", "Republic of Guinea[y]"),
	(null, null, 1, "Guinea-Bissau", "Republic of Guinea-Bissau"),
	(null, null, 1, "Guyana", "Co-operative Republic of Guyana"),
	(null, null, 1, "Haiti", "Republic of Haiti"),
	(null, null, 1, "Honduras", "Republic of Honduras"),
	(null, null, 1, "Hungary", null),
	(null, null, 1, "Iceland", "Republic of Iceland"),
	(null, null, 1, "India", "Republic of India"),
	(null, null, 1, "Indonesia", "Republic of Indonesia"),
	(null, null, 1, "Iran", "Islamic Republic of Iran"),
	(null, null, 1, "Iraq", "Republic of Iraq"),
	(null, null, 1, "Ireland", null),
	(null, null, 1, "Israel", "State of Israel"),
	(null, null, 1, "Italy", "Italian Republic"),
	(null, null, 1, "Ivory Coast", "Republic of Côte d'Ivoire"),
	(null, null, 1, "Jamaica", null),
	(null, null, 1, "Japan", null),
	(null, null, 1, "Jordan", "Hashemite Kingdom of Jordan"),
	(null, null, 1, "Kazakhstan", "Republic of Kazakhstan"),
	(null, null, 1, "Kenya", "Republic of Kenya"),
	(null, null, 1, "Kiribati", "Republic of Kiribati"),
	(null, null, 1, "Korea, North", "Democratic People's Republic of Korea"),
	(null, null, 1, "Korea, South", "Republic of Korea"),
	(null, null, 1, "Kuwait", "State of Kuwait"),
	(null, null, 1, "Kyrgyzstan", "Kyrgyz Republic"),
	(null, null, 1, "Laos", "Lao People's Democratic Republic"),
	(null, null, 1, "Latvia", "Republic of Latvia"),
	(null, null, 1, "Lebanon", "Lebanese Republic"),
	(null, null, 1, "Lesotho", "Kingdom of Lesotho"),
	(null, null, 1, "Liberia", "Republic of Liberia"),
	(null, null, 1, "Libya", "State of Libya"),
	(null, null, 1, "Liechtenstein", "Principality of Liechtenstein"),
	(null, null, 1, "Lithuania", "Republic of Lithuania"),
	(null, null, 1, "Luxembourg", "Grand Duchy of Luxembourg"),
	(null, null, 1, "Madagascar", "Republic of Madagascar"),
	(null, null, 1, "Malawi", "Republic of Malawi"),
	(null, null, 1, "Malaysia", "Federation of Malaysia"),
	(null, null, 1, "Maldives", "Republic of Maldives"),
	(null, null, 1, "Mali", "Republic of Mali"),
	(null, null, 1, "Malta", "Republic of Malta"),
	(null, null, 1, "Marshall Islands", "Republic of the Marshall Islands"),
	(null, null, 1, "Mauritania", "Islamic Republic of Mauritania"),
	(null, null, 1, "Mauritius", "Republic of Mauritius"),
	(null, null, 1, "Mexico", "United Mexican States"),
	(null, null, 1, "Micronesia", "Federated States of Micronesia"),
	(null, null, 1, "Moldova", "Republic of Moldova"),
	(null, null, 1, "Monaco", "Principality of Monaco"),
	(null, null, 1, "Mongolia", null),
	(null, null, 1, "Montenegro", null),
	(null, null, 1, "Morocco", "Kingdom of Morocco"),
	(null, null, 1, "Mozambique", "Republic of Mozambique"),
	(null, null, 1, "Myanmar", "Republic of the Union of Myanmar"),
	(null, null, 1, "Namibia", "Republic of Namibia"),
	(null, null, 1, "Nauru", "Republic of Nauru"),
	(null, null, 1, "Nepal", "Federal Democratic Republic of Nepal"),
	(null, null, 1, "Netherlands", "Kingdom of the Netherlands"),
	(null, null, 1, "New Zealand", null),
	(null, null, 1, "Nicaragua", "Republic of Nicaragua"),
	(null, null, 1, "Niger", "Republic of the Niger"),
	(null, null, 1, "Nigeria", "Federal Republic of Nigeria"),
	(null, null, 1, "North Macedonia", "Republic of North Macedonia"),
	(null, null, 1, "Norway", "Kingdom of Norway"),
	(null, null, 1, "Oman", "Sultanate of Oman"),
	(null, null, 1, "Pakistan", "Islamic Republic of Pakistan"),
	(null, null, 1, "Palau", "Republic of Palau"),
	(null, null, 1, "Palestine", "State of Palestine"),
	(null, null, 1, "Panama", "Republic of Panama"),
	(null, null, 1, "Papua New Guinea", "Independent State of Papua New Guinea"),
	(null, null, 1, "Paraguay", "Republic of Paraguay"),
	(null, null, 1, "Peru", "Republic of Peru"),
	(null, null, 1, "Philippines", "Republic of the Philippines"),
	(null, null, 1, "Poland", "Republic of Poland"),
	(null, null, 1, "Portugal", "Portuguese Republic"),
	(null, null, 1, "Qatar", "State of Qatar"),
	(null, null, 1, "Romania", null),
	(null, null, 1, "Russia", "Russian Federation"),
	(null, null, 1, "Rwanda", "Republic of Rwanda"),
	(null, null, 1, "Saint Kitts and Nevis", "Federation of Saint Christopher and Nevis"),
	(null, null, 1, "Saint Lucia", null),
	(null, null, 1, "Saint Vincent and the Grenadines", null),
	(null, null, 1, "Samoa", "Independent State of Samoa"),
	(null, null, 1, "San Marino", "Republic of San Marino"),
	(null, null, 1, "São Tomé and Príncipe", "Democratic Republic of São Tomé and Príncipe"),
	(null, null, 1, "Saudi Arabia", "Kingdom of Saudi Arabia"),
	(null, null, 1, "Senegal", "Republic of Senegal"),
	(null, null, 1, "Serbia", "Republic of Serbia"),
	(null, null, 1, "Seychelles", "Republic of Seychelles"),
	(null, null, 1, "Sierra Leone", "Republic of Sierra Leone"),
	(null, null, 1, "Singapore", "Republic of Singapore"),
	(null, null, 1, "Slovakia", "Slovak Republic"),
	(null, null, 1, "Slovenia", "Republic of Slovenia"),
	(null, null, 1, "Solomon Islands", null),
	(null, null, 1, "Somalia", "Federal Republic of Somalia"),
	(null, null, 1, "South Africa", "Republic of South Africa"),
	(null, null, 1, "South Sudan", "Republic of South Sudan"),
	(null, null, 1, "Spain", "Kingdom of Spain"),
	(null, null, 1, "Sri Lanka", "Democratic Socialist Republic of Sri Lanka"),
	(null, null, 1, "Sudan", "Republic of the Sudan"),
	(null, null, 1, "Suriname", "Republic of Suriname"),
	(null, null, 1, "Sweden", "Kingdom of Sweden"),
	(null, null, 1, "Switzerland", "Swiss Confederation"),
	(null, null, 1, "Syria", "Syrian Arab Republic"),
	(null, null, 1, "Taiwan", null),
	(null, null, 1, "Tajikistan", "Republic of Tajikistan"),
	(null, null, 1, "Tanzania", "United Republic of Tanzania"),
	(null, null, 1, "Thailand", "Kingdom of Thailand"),
	(null, null, 1, "Togo", "Togolese Republic"),
	(null, null, 1, "Tonga", "Kingdom of Tonga"),
	(null, null, 1, "Trinidad and Tobago", "Republic of Trinidad and Tobago"),
	(null, null, 1, "Tunisia", "Republic of Tunisia"),
	(null, null, 1, "Turkey", "Republic of Turkey"),
	(null, null, 1, "Turkmenistan", "Republic of Turkmenistan"),
	(null, null, 1, "Tuvalu", null),
	(null, null, 1, "Uganda", "Republic of Uganda"),
	(null, null, 1, "Ukraine", null),
	(null, null, 1, "United Arab Emirates", null),
	(null, null, 1, "United Kingdom", "United Kingdom of Great Britain and Northern Ireland"),
	(null, null, 1, "United States", "United States of America"),
	(null, null, 1, "Uruguay", "Oriental Republic of Uruguay"),
	(null, null, 1, "Uzbekistan", "Republic of Uzbekistan"),
	(null, null, 1, "Vanuatu", "Republic of Vanuatu"),
	(null, null, 1, "Vatican City", "Holy See of Vatican City"),
	(null, null, 1, "Venezuela", "Bolivarian Republic of Venezuela"),
	(null, null, 1, "Vietnam", "Socialist Republic of Vietnam"),
	(null, null, 1, "Western Sahara", "Sahrawi Arab Democratic Republic"),
	(null, null, 1, "Yemen", "Republic of Yemen"),
	(null, null, 1, "Zambia", "Republic of Zambia"),
	(null, null, 1, "Zimbabwe", "Republic of Zimbabwe");

commit;